export const mockData = {
  user: {
    id: 0,
    firstName: 'Yazeed',
    lastName: 'Bzadough',
    email: 'ybzadough@gmail.com',
    themeColor: '#4d76fd',
    profilePicture: '/logo192.png',
  },
  folders: [
    {
      name: 'marketing',
      tasks: [
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2020-01-01').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2020-02-22').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2020-04-05').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2019-11-27').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2020-05-10').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
        {
          title: 'Write an article about design',
          isComplete: true,
          created: new Date('2020-03-01').getTime(),
          description: '',
          attachments: [],
          activity: [],
        },
      ],
    },
    {
      name: 'design',
      tasks: [],
    },
    {
      name: 'development',
      tasks: [],
    },
    {
      name: 'management',
      tasks: [],
    },
  ],
  team: [
    {
      id: 1,
      firstName: 'Yazeed',
      lastName: 'Bzadough',
      email: 'ybzadough@gmail.com',
      themeColor: '#4d76fd',
      profilePicture: '/logo192.png',
    },
    {
      id: 2,
      firstName: 'Yazeed',
      lastName: 'Bzadough',
      email: 'ybzadough@gmail.com',
      themeColor: '#4d76fd',
      profilePicture: '/logo192.png',
    },
    {
      id: 3,
      firstName: 'Yazeed',
      lastName: 'Bzadough',
      email: 'ybzadough@gmail.com',
      themeColor: '#4d76fd',
      profilePicture: '/logo192.png',
    },
    {
      id: 4,
      firstName: 'Yazeed',
      lastName: 'Bzadough',
      email: 'ybzadough@gmail.com',
      themeColor: '#4d76fd',
      profilePicture: '/logo192.png',
    },
    {
      id: 5,
      firstName: 'Yazeed',
      lastName: 'Bzadough',
      email: 'ybzadough@gmail.com',
      themeColor: '#4d76fd',
      profilePicture: '/logo192.png',
    },
  ],
};
